apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tinyproxy
  name: tinyproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyproxy-deployment
spec:
  selector:
    matchLabels:
      app: tinyproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: tinyproxy
    spec:
      containers:
      - name: tinyproxy
        image: gcr.io/stolos-dev/tinyproxy:latest
        ports:
        - containerPort: 8888
      serviceAccount: tinyproxy
---
apiVersion: v1
kind: Service
metadata:
  name: tinyproxy-service
spec:
  selector:
    app: tinyproxy
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8888

